# Generated by Django 4.1.5 on 2023-04-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_create_at_recipe_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_publisched',
            new_name='is_published',
        ),
    ]
